spring:
  application:
    name: springcloud-zuul


server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: springcloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: springcloud-web-admin-feign